#!/bin/bash

set -e

# standalone compilation
ln -sf app.src2 app_tools/app.src
make -j APPLANG=fr # V=1
ln -sf app.src1 app_tools/app.src

# remove relocations in the app (save about 600Ko)
g++ -O2 reloc.cc -o reloc
cd bin
../reloc DEMO.bin
cd ..

# build 8ek and segments appvar for INST
python3 app_tools/make_8ek.py bin/_DEMO.bin bin/DEMO.8ek DEMO
python3 app_tools/make_segments.py bin/_DEMO.bin bin
echo "Francais done"

# local install, assumes you have a link to a folder shared/ti with artifice
if [ ! -d "shared/ti" ]
then
  echo "./shared/ti/ folder didn't exist, creating it..."
  mkdir -p shared/ti/
fi
cp bin/DEMO.8* shared/ti/
rm -rf shared/ti/app && mkdir -p shared/ti/app && cp bin/App*x* shared/ti/app
echo "Creating bundle file..."
./bundle FlowCE-fr b83
ls -l shared/ti/DEMO.8ek
