#!/bin/bash
# Assemble tools/asm/ui_blit.asm with CEdev's fasmg and write its machine code as a C array in
# src/ui_blit_code.h. The routine is position independent (relative jumps only) and is called
# through a pointer to that array (ui_font.c): linking an .asm object into the app made the
# installed app hang the OS at boot (2026-10-05, not understood), a const array does not.
# Run in WSL:  bash tools/asm/mkblit.sh
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
CEDEV="${CEDEV:-/home/bell/khicas-review-build/CEdev}"
TMP="$(mktemp -d)"
grep -v -E '^\s*(section|public)\b' "$HERE/ui_blit.asm" > "$TMP/body.asm"
printf "include '%s/meta/commands.alm'\ninclude '%s/meta/ez80.alm'\nassume adl=1\norg 0\ninclude 'body.asm'\n" "$CEDEV" "$CEDEV" > "$TMP/top.asm"
(cd "$TMP" && "$CEDEV/bin/fasmg" top.asm blit.bin >/dev/null)
{
  echo "// Generated by tools/asm/mkblit.sh from tools/asm/ui_blit.asm (fasmg). Do not edit."
  echo "// void ui_blit2(unsigned char * dst, const unsigned char * bits, unsigned char mi,"
  echo "//               unsigned char w, unsigned char rows, const unsigned char * ramp);"
  echo "static const unsigned char ui_blit2_code[$(stat -c %s "$TMP/blit.bin")] = {"
  xxd -i < "$TMP/blit.bin"
  echo "};"
} > "$REPO/src/ui_blit_code.h"
rm -rf "$TMP"
echo "wrote src/ui_blit_code.h"
