// Generated by tools/fonts/mkfonts.py. Do not edit.
#ifndef UI_FONTDATA_H
#define UI_FONTDATA_H
#include "ui_font.h"
#ifdef __cplusplus
extern "C" {
#endif
extern const ui_face ui_mu34;
extern const ui_face ui_mi34;
extern const ui_face ui_mu28;
extern const ui_face ui_mi28;
extern const ui_face ui_mu24;
extern const ui_face ui_mi24;
extern const ui_face ui_mu20;
extern const ui_face ui_mi20;
extern const ui_face ui_mu17;
extern const ui_face ui_mi17;
extern const ui_face ui_mu14;
extern const ui_face ui_mi14;
extern const ui_face ui_mu12;
extern const ui_face ui_mi12;
extern const ui_face ui_mu10;
extern const ui_face ui_mi10;
extern const ui_face ui_tr9;
extern const ui_face ui_tb9;
extern const ui_face ui_tr10;
extern const ui_face ui_tb10;
extern const ui_face ui_tr12;
extern const ui_face ui_tb12;
#ifdef __cplusplus
}
#endif
#endif
