// ui_font.h - 4-shade (2-bit) fonts of the Focus interface (data: ui_fontdata.c, generated by
// tools/fonts/mkfonts.py). Text is UTF-8; a glyph missing from a face is skipped (width 0).
#ifndef UI_FONT_H
#define UI_FONT_H

#ifdef __cplusplus
extern "C" {
#endif

// one glyph: code (ASCII, or 0x80 + index of UI_EXTRA in ui_font.c), offset of its 2-bit pixels
// in the face's bits, advance, box size,
// box offset from the pen (ox right, oy down from the baseline: negative = above)
typedef struct { unsigned char code; unsigned short off; unsigned char adv, w, h; signed char ox, oy; } ui_glyph;
// a face: nominal size and layout ascent/descent in pixels, glyphs sorted by code; index: glyph
// position of each code (0x80 + number of extra symbols codes; 255 = missing)
typedef struct { unsigned char size, asc, desc, count; const ui_glyph * glyphs; const unsigned char * bits, * index; } ui_face;

// next code point of UTF-8 text at *s (advances *s); 0 at the end
unsigned ui_utf8(const char ** s, const char * end);
const ui_glyph * ui_glyph_of(const ui_face * f, unsigned cp);
// advance width of s[0,n) (n < 0: up to the terminating 0)
int ui_text_width(const ui_face * f, const char * s, int n);
// draws s[0,n) with its baseline at y, starting at x; ramp: the 4 palette indices of the shades
// (ramp[0] = background, drawn only when opaque). Returns the advance.
int ui_draw_text(const ui_face * f, const char * s, int n, int x, int y, const unsigned char * ramp, int opaque);
int ui_draw_glyph(const ui_face * f, unsigned cp, int x, int y, const unsigned char * ramp, int opaque);
// glyph cp stretched vertically to h rows, its box top at ytop (tall parentheses)
int ui_draw_glyph_v(const ui_face * f, unsigned cp, int x, int ytop, int h, const unsigned char * ramp);

#ifdef __cplusplus
}
#endif
#endif
